language: node_js
node_js:
  - '10'
  - '8'
sudo: required
cache: npm
services:
  - docker
env:
  global:
    # - DEBUG=kafkajs:*
    - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
before_install:
  # - sudo apt-get update
  # - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker-compose -f docker/docker-compose.yml up -d
before_script:
  - npm start
after_failure:
  - docker ps
  - docker-compose logs
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
